# Generated by Django 4.1.1 on 2022-09-17 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0005_alter_library_name'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrowed_books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('borrowed_library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library.library')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BorrowedUser',
                'verbose_name_plural': 'BorrowedUsers',
                'ordering': ['-created_at'],
            },
        ),
    ]
