# Generated by Django 4.1.1 on 2022-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borroweduser_borrowed_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweduser',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
