# Generated by Django 4.1.1 on 2022-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borroweduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweduser',
            name='email_address',
            field=models.EmailField(max_length=50),
        ),
    ]
