# Generated by Django 4.1.1 on 2022-09-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_remove_borroweduser_borrowed_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweduser',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
