# Generated by Django 4.1.1 on 2022-09-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0003_alter_borroweduser_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borroweduser',
            name='slug',
        ),
    ]
