# Generated by Django 4.1.1 on 2022-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('BORROWER', 'BORROWER'), ('LIBRARIAN', 'LIBRARIAN')], default='BORROWER', max_length=10),
        ),
    ]
