# Generated by Django 4.1.1 on 2022-09-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='return_date',
        ),
    ]
